"""Add categories and update models

Revision ID: f3ab8e30b8af
Revises: 884fa1ae68ec
Create Date: 2025-06-10 12:25:58.915413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ab8e30b8af'
down_revision: Union[str, None] = '884fa1ae68ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('book_category',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'category_id')
    )
    op.add_column('book', sa.Column('publisher', sa.String(length=100), nullable=True))
    op.add_column('book', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('book', sa.Column('pages', sa.Integer(), nullable=True))
    op.create_index('idx_book_title_author', 'book', ['title', 'author'], unique=False)
    op.add_column('loan', sa.Column('extended', sa.Boolean(), nullable=False))
    op.create_index('idx_loan_book_id', 'loan', ['book_id'], unique=False)
    op.create_index('idx_loan_return_date', 'loan', ['return_date'], unique=False)
    op.create_index('idx_loan_user_id', 'loan', ['user_id'], unique=False)
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    op.drop_index('idx_loan_user_id', table_name='loan')
    op.drop_index('idx_loan_return_date', table_name='loan')
    op.drop_index('idx_loan_book_id', table_name='loan')
    op.drop_column('loan', 'extended')
    op.drop_index('idx_book_title_author', table_name='book')
    op.drop_column('book', 'pages')
    op.drop_column('book', 'language')
    op.drop_column('book', 'publisher')
    op.drop_table('book_category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
